package org.example.enums;

public enum Permisos {
    CREAR_ESPACIO,
    ELIMINAR_ESPACIO,
    MODIFICAR_ESPACIO,
    VER_ESPACIOS,
    VER_AULAS,
    VER_LABORATORIOS,
    CREAR_RESERVA,
    MODIFICAR_RESERVA,
    ELIMINAR_RESERVA,
    VER_RESERVAS,
    SOLICITAR_CAMBIO,
    VER_SOLICITUDES_CAMBIO,
    GESTIORNAR_CAMBIOS

}
