package enums;

public enum BloqueHorario {

    MANIANA_PRIMER_BLOQUE,
    MANIANA_SEGUNDO_BLOQUE,
    TARDE_PRIMER_BLOQUE,
    TARDE_SEGUNDO_BLOQUE,
    NOCHE_PRIMER_BLOQUE,
    NOCHE_SEGUNDO_BLOQUE

}

